#ifndef NEURON_H
#define NEURON_H
using namespace std;
#include <vector>
#include <fstream>

class Neuron
{
	private:
	double potential_; //!< membrane potential of the neuron
	double h_; //!< time step of simulation in ms
	double Iext_; //!< external current- used when their is no backdroung stimulation
	int spikecount_; //!< count keeper of the numbers of spike generated by the neuron
	vector <double> spikeTime_; //!< vector that keeps track of the spike timees of the neurons in ms
	double taux_; //!< temps caracteristique taux=Resistance*C
	double tauxRefractory_; //!< refractory time in ms
	double conductivity_; //!< mebrane conductivity
	double Res_; //!< membrane resistance
	int clock_; //!< neuron internal clock to keep track of time- number of h steps
	bool isSpiking_; //!< boolean test to know if the neuron has spiked.
	int Delay_; //!< Delay time initialised in contructor in number of time steps
	vector <int> Buffer_; //!< keeps track of the number of spikes received at each time step
	double J_; //!< the potential increase of the mebran whne it receives a spike
						//!<(including from rest of the brain)
	double threshold_;//!< membrane potential above which the neuron spikes
	double ref_time_;//!< refractory time in time steps
	vector <int> connected_with_;//!< neurons that are connected with it using their index
	bool isExcitory;//!< check is the neuron is of type Excitory

	public:
	//!<constructor and destructor
	Neuron ();
	~Neuron ();

	//!< Getteurs et Setteurs
	/**
	@return double potential_
	*/
	double getPotential() const;

	/**
	@return int spikecount_
	*/
	int getSpikecount() const;

	/**
	@return vector spikeTime_
	*/
	vector <double> getSpiketime() const;

	/**
	@return bool isSpiking_
	*/
	bool getisSpiking() const;

	/**
	@return vector connected_with_
	*/
	vector<int> getConnection() const;
	/**
	@return vector connected_with_
	*/

	void setSpikecount ();//!< sets the spike count of the neuron

	/**
	@param double time
	places spike time in the attribut spikeTime_
	*/
	void setSpikeTime(double t);//!< sets the time of the spike in the vector spikeTime_

	/**
	@param int const neuron_index
	sets the connected_with_ vector
	*/
	void setConnexion (int const neuron_index);//!< sets the connected_with_ vector
	void setBuffer();//!< sets the Buffer_ of the target neuron at the correct place
	void setBool();//!< sets boolean isExcitory to true for Excitory neurons
	void setJ_();//!< sets the J_ value for inhibitory neurons (J=-0.5)


	//!< Methodes
	/**
	@param double& simtime, vector<Neuron>& neuron_sim;
	update the potential of the neuron depending on if its in refractory time or not.
	It also sets the buffer of the target neurons if it has spiked
	*/
	void update(double& simtime,vector<Neuron>& neuron_sim);
	/**
	@param vector<Neuron>& neuron_sim
	puts spike in the buffer of the neurons connected with it
	*/
	void give_spike(vector<Neuron>& neuron_sim);

};

#endif
